### ISSUE TITLE
Identifier "security" is not defined.

### ISSUE THREAD

**Issue by LocoNeko** [DaveC49/SimpleUser-Silex2#2]
Hi,

Thanks a lot for porting Jason's SImpleUser to Silex 2 ! I am relying on it for my own app and didn't know how to manage the upgrade.

However, I'm now running into one problem : attempting to create a new account results in the error :

_Identifier "security" is not defined._

And when trying to sign in with existing users, I get :

_Invalid credentials._

Existing users that are already logged in do not face any problem, so I suspect some problem at identification.

If you have any clue, let me know !

**Comment by LocoNeko** [comment]
Sorry, there was nothing wrong with the app. Turns out the previous users' hash in the database were not compatible with the latest version. After creating new users I was actually able to login properly once I cleared my browser's cache. Users created with the previous version became unusable though.

Anyway, thanks for the great work !

**Comment by sintro** [comment]
Actually, this IS a problem.
Silex now has another interface with Security provider, and we can not use 
`app['security']->getToken()` anymore like here https://github.com/DaveC49/SimpleUser-Silex2/blob/master/src/SimpleUser/UserManager.php#L741
The correct way now is `app['security.token_storage']->getToken()`
Btw, the next line in this method is also broken, as it tries to call 'getKey' from `AnonymousToken` class, which does not have one. Don't know how to fix it.
Looks like for me it is working solution when you change getKey to getSectret, as it returns the only one firewall's name ('secured_area') for me. 
And weird, after successful logging in the web profiler crashes.

**Comment by DaveC49** [comment]
Hi Dmitry,
Thanks for bringing these issues to my attention. I must confess to doing the bare minimum when porting  SimpleUser to Silex 2. I have moved on from the project, I was using Simple User in but will include your corrections and try to set up a test framework .
David
