### ISSUE TITLE
Security encoders

### ISSUE THREAD

**Issue by Nico-h** [DaveC49/SimpleUser-Silex2#4]
Hi,

If I'm correct, as silex 2.2, now in UserManager, getEncoder is set in the security.encoder_factory service

```
    protected function getEncoder(UserInterface $user)
    {
        return $this->app['security.encoder_factory']->getEncoder($user);
    }
```

**Comment by javiermadueno** [comment]
Maybe we should create a tag for Silex > v2.0 and another one for Silex > v2.2

**Comment by DaveC49** [comment]
Javier, Nico-h  
I have taggesd the releases as suggested by Javier.
